import { useEffect, useState } from 'react'
import { useTerminal } from '../state/TerminalContext'
import { resolveFunction } from '../state/registry'

/** Bottom status strip: current screen, data disclaimer, shortcuts, clock. */
export default function StatusBar() {
  const { view } = useTerminal()
  const [now, setNow] = useState(() => new Date())
  useEffect(() => {
    const id = setInterval(() => setNow(new Date()), 1000)
    return () => clearInterval(id)
  }, [])

  const fn = resolveFunction(view.func)
  return (
    <footer className="flex items-center gap-3 px-3 h-6 border-t border-line bg-black text-[10px] text-zinc-500 shrink-0">
      <span className="text-amber font-bold tracking-widest">
        {view.ticker && fn?.requiresSecurity ? `${view.ticker} ` : ''}
        {view.func}
      </span>
      <span className="hidden sm:inline">{fn?.name}</span>
      <span className="text-zinc-700">|</span>
      <span className="text-warn font-semibold tracking-wider" title="All prices and financials are generated by a deterministic simulation engine for demonstration. Connect a market-data adapter for live use.">
        ⚠ SIMULATED DATA
      </span>
      <span className="ml-auto hidden md:flex gap-3">
        <span><kbd className="text-zinc-400">/</kbd> command</span>
        <span><kbd className="text-zinc-400">F1–F8</kbd> screens</span>
        <span><kbd className="text-zinc-400">Alt+←</kbd> back</span>
      </span>
      <span className="text-zinc-300 tabular-nums">
        {now.toLocaleTimeString('en-US', { hour12: false })} ET
      </span>
    </footer>
  )
}
